# Generated by Django 6.0.4 on 2026-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('insurance_tier__in', ['Bronze', 'Silver', 'Gold'])), name='users_insurance_tier_valid_choice'),
        ),
    ]
