# Generated by Django 6.0.4 on 2026-04-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_outbox_idempotency_and_dead_letter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN', 'User Login'), ('AUTH_SIGNUP', 'User Signup'), ('AUTH_LOGOUT', 'User Logout'), ('AUTH_FAILURE', 'Authentication Failure'), ('SCHEDULING_CREATE', 'Appointment Created'), ('SCHEDULING_UPDATE', 'Appointment Updated'), ('SCHEDULING_CANCEL', 'Appointment Cancelled'), ('CHAT_START', 'Chat Session Started'), ('CHAT_MESSAGE', 'Chat Message Processed'), ('TOOL_EXECUTION', 'Tool Executed'), ('TOOL_FAILURE', 'Tool Failed'), ('AI_EMERGENCY', 'Emergency Override Triggered'), ('AI_OUT_OF_SCOPE', 'Out-of-Scope Detection')], max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('NOTICE', 'Notice'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('correlation_id', models.CharField(db_index=True, help_text='Trace ID connecting related events across request lifecycle', max_length=64)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected (e.g., appointment, chat_session)', max_length=64)),
                ('resource_id', models.CharField(blank=True, help_text='ID of resource affected', max_length=255)),
                ('action', models.CharField(blank=True, help_text='Specific action taken', max_length=255)),
                ('reason_code', models.CharField(blank=True, help_text='Machine-readable reason/error code', max_length=64)),
                ('details', models.JSONField(default=dict, help_text='Structured event details (PHI-sensitive fields should be redacted)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['correlation_id', '-timestamp'], name='core_auditevn_correlat_idx'),
                    models.Index(fields=['event_type', '-timestamp'], name='core_auditevn_event_ty_idx'),
                    models.Index(fields=['user', '-timestamp'], name='core_auditevn_user_id_idx'),
                ],
            },
        ),
    ]
