# Generated by Django 6.0.4 on 2026-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('content__regex', '^\\s*$'), _negated=True), name='chat_message_content_not_blank'),
        ),
    ]
