# Generated by Django 6.0.4 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_chat_message_content_not_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(
                condition=models.Q(('role', 'user'), ('request_id__isnull', False)),
                fields=('session', 'request_id'),
                name='chat_user_request_id_unique_per_session',
            ),
        ),
    ]
