# Generated by Django 6.0.4 on 2026-04-11 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_message_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=32)),
                ('selection', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='chatmessage',
            name='chat_user_request_id_unique_per_session',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_kind',
            field=models.CharField(choices=[('text', 'Text'), ('providers', 'Providers'), ('availability', 'Availability'), ('appointments', 'Appointments'), ('json', 'JSON')], default='text', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'user'), models.Q(('request_id__isnull', True), _negated=True)), fields=('session', 'request_id'), name='chat_user_request_id_unique_per_session'),
        ),
        migrations.AddField(
            model_name='structuredinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='structuredinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'interaction_id'), name='structured_interaction_user_unique'),
        ),
    ]
