# Generated by Django 6.0.4 on 2026-04-09 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
