# Generated by Django 6.0.4 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms_summary',
            field=models.TextField(default=''),
        ),
    ]
