# Generated by Django 6.0.4 on 2026-04-09 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_appointment_context_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('availability_dtstart', models.DateTimeField()),
                ('availability_rrule', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.provider'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user_id', 'time_slot'], name='scheduling__user_id_2ce438_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider_id', 'time_slot'], name='scheduling__provide_ade94c_idx'),
        ),
    ]
