# Generated by Django 6.0.4 on 2026-04-11 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_provider_unique_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('rrule__regex', '^\\s*$'), _negated=True), name='appointment_rrule_not_blank'),
        ),
    ]
