from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from chatbot.features.scheduling.models import Appointment, Provider


class SchedulingUnitOfWork(Protocol):
    def __enter__(self) -> SchedulingUnitOfWork: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool | None: ...

    def get_user(self, user_id: int) -> Any: ...
    def get_provider(self, provider_id: int) -> Provider | None: ...
    def list_providers(self) -> list[Provider]: ...

    def list_all_appointments(self) -> list[Appointment]: ...
    def list_provider_appointments(self, provider_id: int) -> list[Appointment]: ...
    def list_future_user_appointments(
        self,
        *,
        user_id: int,
        from_datetime: datetime,
    ) -> list[Appointment]: ...

    def provider_has_conflict(
        self,
        *,
        provider_id: int,
        time_slot: datetime,
        exclude_appointment_id: int | None = None,
    ) -> bool: ...

    def get_user_appointment(self, *, user_id: int, appointment_id: int) -> Appointment | None: ...
    def create_appointment(self, **kwargs: Any) -> Appointment: ...
    def save_appointment(self, appointment: Appointment, *, update_fields: list[str]) -> None: ...
    def delete_user_appointment(self, *, user_id: int, appointment_id: int) -> bool: ...
